spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.google.com
          predicates:
            - Query=url, google
        - id: miss_route
          uri: https://www.nba.com
          predicates:
            - Query=url, nba